name: Automated Build and Execution



jobs:
  build-and-execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your Python version

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  

      - name: Run Automated Task
        run: python slots.py  # Replace with your script name

  stop-automation:
    runs-on: ubuntu-latest
    needs: build-and-execute
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Stop Automation
        run: |
          # Add logic to stop automation based on the presence of a file or email trigger
          # For example, check for the existence of a file
          if [ -e "stop_automation.txt" ]; then
            echo "Automation stopped by file."
            exit 0
          fi
          
          # Alternatively, you can check for an email trigger or any other condition

